//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJECT_MANAGEMENTEntities1 : DbContext
    {
        public PROJECT_MANAGEMENTEntities1()
            : base("name=PROJECT_MANAGEMENTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Job_Title> Job_Title { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<User_Projects> User_Projects { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
